cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://erudio.com.br
security:   
  jwt:
    token:
        secret-key: 53cr37
        expire-lenght: 360000
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:mysql://localhost:5432/bucetinha?useTimezone=true&serverTimezone=UTC
    username: rpdv
    password: rpdvwin1064
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
springdoc:
  pathsToMatch: /api/**/v1/**
  swagger-ui:
    use-root-path: true
    
   #org.postgresql.Driver
#jdbc:postgresql://localhost:5432/bucetinha
#rpdv
#rpdvwin1064